name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 20 * * 5  # 北京时间星期六凌晨4点，定时触发

jobs:

    IPQ60XX-LibWrt:
      uses: ./.github/workflows/IPQ60XX-LibWrt.yml

    IPQ807X-LibWrt:
      uses: ./.github/workflows/IPQ807X-LibWrt.yml

    Arthur-Athena-Taiyi-ImmortalWrt:
      uses: ./.github/workflows/Arthur&Athena&Taiyi-ImmortalWrt.yml

    x86-64-ImmortalWrt:
      uses: ./.github/workflows/x86-64-ImmortalWrt.yml

    MT798X-ImmortalWrt:
      uses: ./.github/workflows/MT798X-ImmortalWrt.yml

